---
conditions:
  all:
  # Title starts with ‘[bug]’
  - fact: payload.issue.title          
    operator: regex
    value: ^\[bug\]
  # Prevent loops
  - fact: payload.sender.type
    operator: notEqual
    value: Bot
event:
  type: createIssueLabels
  params:
    data:
    - bug
    - question
