---
conditions:
  all:
    - fact: payload.issue.user.login
      operator: equal
      value: jefeish

event:  
  type: create two comments
  handlers:
    - name: issuesCreateComment
      params:
        comment: Thank you for creating this issue! This is a Client-Side Rule!
    - name: issuesCreateComment
      params:
        comment: another ...This is a Client-Side Rule!

# default is '1'
priority: 1
