---
conditions:
  all:
    - fact: payload.issue.user.login
      operator: equal
      value: jefeish

event:  
  - type: issuesCreateComment
    params:
      comment: Thank you for creating this issue! This is a Client-Side Rule!
event: 
  - type: issuesCreateComment
    params:
      comment: another Client-Side Rule!

# default is '1'
priority: 1
