---
conditions:
  all:
    - fact: payload.issue.user.login
      operator: equal
      value: jefeish
  # Prevent loops
    - fact: payload.sender.type
      operator: notEqual
      value: Bot
event:
  type: issuesCreateComment
  params:
    comment: Thank you for creating this issue! This is a Client-Side Rule!

# default is '1'
priority: 1
